@startmindmap 中国
* 中国 VS 美国

** 军事
*** 落后
**** 航空母舰
*** 差别不大
**** 四代机
**** 导弹
**** 舰载机
*** 领先
**** 导弹驱逐舰
**** 中程导弹


** 航空航天
*** 落后
**** 航空发动机
**** 运载火箭
**** 深空探索
*** 差别不大
**** 大飞机
*** 领先
**** 空间站


** 芯片
*** 落后
**** 芯片制造
***** 光刻机
***** 代工厂
**** 芯片封装
**** EDA软件
**** 行业芯片
***** 通用计算芯片CPU
***** 图形芯片GPU
***** 存储芯片
*** 差别不大
**** 芯片设计
**** 行业芯片
***** 指纹芯片
***** AI芯片
***** IoT芯片
*** 领先


** 汽车
*** 落后
**** 燃油整车
*** 差别不大
**** 汽车供应商
*** 领先
**** 新能源整车
**** 新能源车电池
**** 车机系统


** IT
*** 落后
**** 操作系统
**** 游戏
**** 专业软件
***** matlab
***** 图形软件
***** 工业设计软件
*** 差别不大
**** 人工智能
**** 电子商务
**** 社交网络
**** 云计算
**** 智能手机
*** 领先


** 生物医药
*** 落后
*** 差别不大
*** 领先

** 其它
*** 落后
**** 仪器仪表(科研、工业、医疗)
**** 医疗器械
**** 农业机械
**** 高端机床
*** 差别不大
**** 核聚变装置
**** 量子计算
**** 工程机械
**** 电子元器件(蓝牙、声学器件、摄像头、电阻电容等)
**** 工业机器人
**** 显示面板
*** 领先
**** 高铁
**** 光伏
**** 5G
**** 特高压输电技术

@endmindmap