@startmindmap 未来

* 未来
** 大过滤器
*** 核战争
*** 人类肉体限制
*** 知识膨胀,人有限寿命无法掌握推动科技进步的所有知识
*** 沉迷虚拟世界
*** 低生育率
*** 自然灾变，例如伽马射线暴
*** 末日病毒
*** AI取代人类

** 星际航行
*** 曲率引擎
*** 虫洞
*** 太空天梯
*** 太阳帆
*** 超光速
**** 不可行,相对论限制

** 能源
*** 可控核聚变
*** 戴森球
**** 低级文明建不了,高级文明没必要
*** 正反物质湮灭
*** 室温超导


** 信息
*** 量子通信

** 物质
*** 人体
**** 机械生命体
**** 意识上传
**** 基因改造

** 人类社会
*** 中国
**** 人口向多个大城市集中
*** 世界
**** 全球资源向中美集中


@endmindmap