@startmindmap 规划

* 计划

** 挣钱

*** 工作

*** 投资
**** 定期存款
**** 股票
**** 房子
***** 充分条件
****** 工作变更有换房需求
****** 新房
****** 现房
****** 楼高15层以下
****** 得房率90%以上或取消公摊

***** 必要条件
****** 商贷利率4以下
****** 紧临地铁
****** 房产税出台

***** 加分项
****** 好物业
****** 同小区业主素质
****** 自定义装修
****** 车位赠送

*** 副业
**** 无



** 娱乐&消费
*** 游戏
**** space engine
**** 炉石传说
**** 暗黑破坏神4
**** 魔兽争霸3
**** dota2

*** 读书
*** 视频
*** 电影
*** 音乐
*** 旅行
*** 运动
**** 羽毛球
**** 跳绳
**** 篮球

*** 车
**** 换车
***** 自动驾驶
***** 纯电
***** 有车位


** 可可
*** 问题
**** 养娃观点不一致产生的内耗.传统和科学养娃的矛盾:传统的养娃方式也就最近几十年才有的.
**** 人为的制造过多的任务.
**** 空间狭小独立空间有限.
**** 政府公共服务太烂.

*** 原则
**** 以大人为中心,不是以孩子为中心:孩子的生活习惯很容易改变,大人改变很难.
**** 衣食住行简化,思想教育精致
**** 培养独立人格,不是依附人格
**** 养孩子要有定好规矩,不能轻易打破,孩子的天性会不断试探大人的底线,这是他们学习行为边界的天然手段.孩子会不断破坏规则观察你的反应.
**** “顺便”思路,例如:买菜的时候顺便遛娃,洗澡的时候顺便给孩子洗,做饭的时候顺便把孩子的做出来.

*** 生活
**** 无

*** 教育
**** 不能以金钱作为奖励,类似工资一样定期发钱,养成记账的习惯



@endmindmap