@startmindmap 中国

<style>
mindmapDiagram {
  .a {
    BackgroundColor lightgreen
  }
  .c {
    BackgroundColor #FFBBCC
  }
  .b {
    BackgroundColor lightblue
  }
}
</style>


* 中国
** 问题

*** 住房 <<c>>
**** 高房价
***** 极高的房价收入比
***** 土地财政,政府高价卖地,限制土地供应推高房价
***** 高于大多数国家的房贷利率

**** 房产制度缺陷
***** 缺少房产税调节房价
***** 公摊面积
***** 租售不同权
***** 期房制度,造成烂尾楼
***** 社区管理交给物业,政府不作为

**** 其它
***** 高层建筑,未来难以维护
***** 车位需要购买


*** 教育 <<c>>
**** 高考各地试题不一样
****: 高考各省招生人数不一样
方案: 按各省考生人数分配招生名额;
**** 学区房制度,教育不公平


*** 医疗 <<c>>
**** 医院有盈利指标
**** 医保有额度指标


*** 养老 <<c>>
**** 农村和城市不平等
**** 体制内和体制外不平等
**** 不断延迟退休


*** 法制 <<c>>
**** 企业
***** 没有落实劳动法,996加班文化盛行
***** 黄色工会
***** 私企没有完整或足额缴纳五险一金

**** 政府
***** 人治大于法治,党规大于国法
***** 实行社会主义,实际是官僚资本主义,公有制为主体的经济,实际都是国有,不是民有
***** 公权力不透明,决策过程不公开,财政不公开
***** 官员财产不公开
***** 缺少信用体系
***** 户籍制度,限制人口流动和发展
***** 没有言论、结社、集会、游行、示威自由
***** 法定节假日调休不合理

**** 税收
***** 个人所得税过高,中产阶级税过重
***** 没有财产税、遗产税

**** 其它
***** 缺少影视分级制度


*** 社会问题现状 <<c>>
**** 生育率骤降,老龄化加剧
**** 贫富差距扩大,社会阶层撕裂,中国有世界上最多的富豪
**** 形式主义,因为独裁导致加剧,对上规避风险,对下规避责任
**** 官僚主义,官本位思想严重
**** 特权阶层,垄断社会资源
**** 高彩礼



** 优点
*** 政策有延续性
*** 完善的基建,对偏远地区持续投入
*** 高铁
*** 没有宗教
*** 外卖电商等生活便利
*** 粮食安全
*** 全产业链
*** 独立主权
*** 上大学成本低
*** 历史悠久,有极高的文化认同
*** 生活基本物资价格稳定



* 美国
** 问题
*** 美食较少
*** 政治正确
*** 种族歧视
*** 教育不平等,公立教育拉胯
*** 医疗成本高昂
*** 枪击案频发
*** 工会制度影响行业发展
*** 高层有法律特权


** 优点
*** 独栋的房子
*** 严格执行劳动法
*** 完善的工会,工人权益有保障
*** 日常生活普及法制
*** 空气好
@endmindmap