@startmindmap 未来

* 未来
** 大过滤器
*** 核战争
*** 人类肉体限制
*** 知识膨胀,人有限寿命无法掌握推动科技进步的所有知识
*** 沉迷虚拟世界
*** 低生育率
*** 自然灾变，例如伽马射线暴

** 星际航行
*** 曲率引擎
*** 虫洞
*** 太空天梯
*** 太阳帆

** 能源
*** 戴森球
*** 正反物质湮灭


** 信息
*** 量子通信

** 物质

** 永生
*** 机械生命体
*** 意识上传
*** 基因改造

@endmindmap