@startmindmap 中国

<style>
mindmapDiagram {
  .a {
    BackgroundColor lightgreen
  }
  .c {
    BackgroundColor #FFBBCC
  }
  .b {
    BackgroundColor lightblue
  }
}
</style>


* 中国
** 问题

*** 住房 <<c>>
**** 极高的房价收入比
**** 公摊面积
**** 高层建筑多,未来难以维护
**** 租售不同权
**** 高于大多数国家的房贷利率
**** 销售期房,造成烂尾楼
**** 土地财政,政府高价卖地,限制土地供应推高房价
**** 车位需要购买
**** 学区房制度


*** 教育 <<c>>
**** 高考各地试题不一样
****: 高考各省招生人数不一样
方案: 按各省考生人数分配招生名额;


*** 医疗 <<c>>
**** 医院有盈利指标
**** 医保有额度指标

*** 三农问题 <<c>>
**** 农民养老金和城市不平等
**** 农村户籍制度限制,无法自由流动

*** 法制 <<c>>
**** 没有落实劳动法,996加班文化盛行
**** 官僚主义,人治大于法治,公权力不透明
**** 缺少全国信用体系
**** 官员财产不公开
**** 黄色工会
**** 没有言论、结社、集会、游行、示威自由
**** 私企没有完整或足额缴纳五险一金
**** 缺少影视分级制度

*** 税收 <<c>>
**** 个人所得税过高,中产阶级税过重
**** 没有财产税、遗产税

*** 社会制度问题 <<c>>
**** 实行社会主义,实际是官僚资本主义,公有制为主体的经济,实际都是国有企业
**** 贫富差距扩大,社会阶层撕裂,中国有世界上最多的富豪
**** 形式主义,因为独裁导致加剧,对上规避风险,对下规避责任
**** 退休金体制内体制外严重不平等

*** 社会问题 <<c>>
**** 极低的生育率
**** 高彩礼
**** 法定节假日调休制度


** 优点
*** 政策有延续性
*** 完善的基建,对偏远地区持续投入
*** 高铁
*** 没有宗教
*** 外卖电商等生活便利
*** 粮食安全
*** 全产业链
*** 独立主权
*** 上大学成本低
*** 历史悠久,有极高的文化认同



* 美国
** 问题
*** 美食较少
*** 政治正确
*** 种族歧视
*** 教育不平等,公立教育拉胯
*** 医疗成本高昂
*** 枪击案频发
*** 工会制度影响行业发展


** 优点
*** 独栋的房子
*** 严格执行劳动法
*** 完善的工会,工会人有保障
*** 日常生活普及法制
*** 空气好
@endmindmap