@startmindmap alibaba
* Alibaba
** 缺点
*** 强势的价值观
*** 官僚思想,老人占据高位


** 优点
*** 完善的Java技术体系
*** 双休,年假长
*** 相对新兴的互联网公司较宽松的工作时间
*** 每年有调薪

** 消失的优点
*** 内部转岗机会(2022机会减少)

** 2023计划
*** 区分业务需求、研发需求、自发需求(多做一些自动化研发,解放自己; 多做监控,保护自己; 多整理数据,证明自己).
*** 不要反感总结、分享, 把总结当成面试历练.
*** 每天抽出时间学习、复习专业内容.
*** 了解团队内、优酷整体的运营系统、技术链路.

@endmindmap