@startmindmap 未来
* 外星人和外星世界
** 生命形式
*** 硅基生命
** 可能的星球
***: 木卫二(欧罗巴)
液态水,被引力拉扯产生的热能;


* 未来
** 大过滤器
*** 核战争
*** 人类肉体限制
*** 知识膨胀,人一生无法掌握所有知识
*** 沉迷虚拟世界
*** 低生育率

** 星际旅行
*** 核爆
*** 曲率引擎
*** 虫洞
*** 太空天梯
*** 太阳帆

** 能源
*** 戴森球
*** 正反物质湮灭

@endmindmap