@startmindmap 中国
* 中国
** 落后
*** 航空航天
**** 航空发动机
**** 大飞机
**** 运载火箭
**** 深空探索

*** 芯片
**** 芯片设计
**** 芯片制造
***** 光刻机
***** 代工厂
**** 芯片封装
**** EDA软件
**** 行业芯片
***** 通用计算芯片CPU
***** 图形芯片GPU
***** 存储芯片

*** 计算机
**** 操作系统
**** 云计算
**** 游戏
*** 军事
**** 航空母舰
**** 舰载机
*** 医疗
**** 检测仪器
*** 传统燃油车
*** 高端机床制造


** 差别不大
*** 计算机
**** 人工智能
**** 电子商务
**** 社交网络
*** 芯片
**** 行业芯片
***** 指纹芯片
***** AI芯片
***** IoT芯片
*** 智能手机
*** 新能源汽车
*** 核聚变装置
*** 军事
**** 导弹驱逐舰
**** 四代机
**** 导弹
**** 量子计算


** 领先
*** 高铁
*** 光伏
*** 5G
*** 特高压输电系统


@endmindmap