@startmindmap 中国

* 物资

** 食物


*** 主粮
**** 米(1年)
**** 面(1年)
**** 酵母(1年)
**** 面条(1年)
**** 方便面(1年)
**** 速冻水饺,馄饨,手抓饼(1年)


*** 蔬菜水果类
**** 豆制品
***** 黄豆(1年)
***** 黑豆(1年)
***** 香干(1年)
***** 素鸡(1年)
***** 腐竹(1年)

**** 蔬菜
***** 土豆(1月/可冷冻)
***** 洋葱(1月/可冷冻)
***** 胡萝卜(1月/可冷冻)
***** 大白菜(1月)
***** 南瓜(1月)
***** 娃娃菜(1星期)
***** 西蓝花(1星期/可冷冻)
***** 花菜(1星期/可冷冻)


**** 水果
***** 苹果(冷藏1个月)
***** 橘子/柑/橙子/西柚(冷藏1个月)


*** 肉蛋奶
**** 鸡蛋(2个月)
**** 奶
***** 奶粉
***** 高温灭菌奶,1年保值期
**** 肉类
***** 猪肉
***** 鸡肉



*** 调料油料
**** 食用油
**** 盐



*** 营养补剂
**** 维生素
**** 钙片





* 生存
** 技巧
*** 尽量从原材料囤起

** 容器
*** 密封袋
*** 抽真空机
*** 密封夹
*** 标签




@endmindmap