@startmindmap 未来
* 时间线

left side

** 1991-2020
*** 1991
**** 1月18日,出生
*** 2009
**** 考入电子科技大学
*** 2013
**** 大学毕业
*** 2015
**** 入职乐视
*** 2017
**** 7月,来到杭州,入职网易
**** 11月,结婚
*** 2019
**** 入职阿里
*** 2020
**** 10月,可可出生


right side

** 2021-2030

*** 2022
**** 社会
***** 人口负增长

*** 2023
**** 自己
***** 争取晋升
**** 科技
***** 苹果汽车,AR产品发布

*** 2024
**** 自己
***** 阿里的未来应该可以看清楚,决定去留
**** 科技
***** 中国月背采样任务
***** 中国小行星采样任务
***** 小米汽车发布


*** 2025
**** 自己
***** 确定未来长时间工作的单位:有明确的上升通道,对大龄程序员友好
**** 科技
***** 美国载人登月


*** 2030
**** 科技
***** 中国月球科研站
***** 美国载人登月
***** spaceX载人登陆火星(极大概率无法实现)

*** 自己
**** 学习英语:外企or出国
*** 社会

*** 科技
**** L4级自动驾驶





** 2031-2040
*** 2035
**** 科技
***** 中国月球科考基地

*** 2037
**** 自己
***** 可可成年

*** 2040
**** 科技
***** 美国载人登陆火星

** 2041-2050

*** 社会
**** 中国老龄化问题开始显现
**** 世界人口峰值:97亿

** 2051-2060
*** 2055
**** 自己
***** 退休

** 2061-2070

** 2071-2080

@endmindmap