@startmindmap 黄金
* 黄金

left side

** 1991
*** 1月18日,出生
** 2009
*** 考入电子科技大学
** 2013
*** 大学毕业
** 2015
*** 入职乐视
** 2017
*** 7月,来到杭州,入职网易
*** 11月,结婚,买房
** 2019
*** 入职阿里
** 2020
*** 1月,新冠疫情
*** 10月,可可出生
** 2022
*** 毫无进步

** 2023
*** 争取晋升
*** 提升英语水平
*** 多读几本书

** 2024
*** 9月,可可幼儿园,3岁

** 2027
*** 9月,可可小学,6岁

** 2032
*** 9月,可可初中,12岁

** 2035
*** 9月,可可高中,15岁

** 2037
*** 10月,可可成年,18岁

** 2038
*** 6月,可可高考,18岁

** 2056
*** 退休


right side

** 2022
*** 社会
**** 2月,俄乌战争爆发
**** 中国人口负增长
**** 12月,新冠疫情封控放开,开始第一轮疫情高峰
*** 科技
**** openAI的chatGPT发布

** 2023
*** 科技
**** 苹果汽车,AR产品发布
**** 搜索引擎改版,chatGPT模式出现
**** spaceX星舰发射成功
*** 社会
**** 经济危机
**** 三四线城市房价下跌
**** 3月,第二轮疫情高峰

** 2024
*** 科技
**** 中国月背采样任务
**** 中国小行星采样任务
**** 星链卫星达1.2万颗
*** 社会
**** 解放台湾
**** 俄乌战争结束,俄罗斯事实战败


** 2025
*** 科技
**** 美国载人登月


** 2030年前
*** 科技
**** 中国月球科研站
**** 飞行汽车开始上市
**** 脑机接口实现突破
**** AI技术开始实际应用于各行各业


** 2035
*** 科技
**** 中国月球科考基地
**** L4级自动驾驶


** 2040年前
*** 科技
**** 美国载人登火
**** 量子计算机商用
**** 核动力火箭研发成功
*** 社会
**** 中国老龄化问题开始显现


** 2050年前
*** 科技
**** 可控核聚变商用


** 2060年前
*** 社会
**** 世界人口峰值:97亿



** 2070年前

@endmindmap