@startmindmap 中国
* 中国
** 问题
*** 房子
**** 房价高
**** 公摊面积
**** 高层建筑多
*** 高考
**** 各地试题不一样
****:各地招生人数不一样
方案:按各省考生人数分配招生名额;
*** 户籍制度
*** 农民养老金问题
*** 没有严格的劳动法
*** 极低的生育率
*** 中产税收过重


-- 优点
--- 政策的延续性
--- 集中力量办大事


* 国外
** 问题
** 优点
@endmindmap