@startmindmap 中国
* 中国
** 问题
*** 房子
****: 房价高
方案: 征收房产税;
**** 公摊面积
**** 高层建筑多,未来难以维护
*** 高考
**** 各地试题不一样
****: 各省招生人数不一样
方案: 按各省考生人数分配招生名额;
*** 户籍制度
*** 农民养老金问题
***: 加班文化盛行
方案: 严格落实劳动法;
*** 极低的生育率
*** 税收制度不健全
*** 法治不健全
*** 医疗系统不合理


-- 优点
--- 政策的延续性
--- 完善的基建
--- 高铁
--- 没有宗教
--- 外卖电商等生活便利


* 国外
** 问题
*** 美食较少

-- 优点
--- 独栋的房子
--- 严格执行劳动法
--- 完善的工会
--- 日常生活普及法制
@endmindmap