@startmindmap 未来
* 未来
** 太空探索
*** 太阳系
**** 月球 
***** 2024:中国月背采样
***** 2025:美国登月
***** 2030:中国月球科考基地
**** 火星
***** 2030:中国取样返回任务,2032返回
***** 2040:美国实现载人登陆火星
**** 小行星
***** 2024:中国小行星取样,2026返回
**** 行星际
***** 2036:中国到达木星
***** 2049:中国到达天王星
*** 星际探索
**** 未来100年都不可能实现太阳系外探索
** 能源
*** 中国估计2050可控核聚变商用
*** 美国估计2099可控核聚变商用
** 生物
** 人类
*** 2050:世界人口峰值97亿
** 科技
*** 2023:苹果汽车、AR设备
*** 2024:小米汽车
*** 2030:L4级自动驾驶
@endmindmap